### ISSUE TITLE
Block.io C++ API?

### ISSUE THREAD

**Issue by zvova7890** [BlockIo/block_io-csharp#10]
Hi. Can you please provide C/C++ API, or do not break exist API every half year? You are using API versioning but broke it forever, so for what reason /v2/ is appear? I'm tired of constantly digging deeper and deeper into the creation of blockchain transactions

**Comment by doersf** [comment]
We will consider providing a library for C/C++. You should, however, be able to code this yourself using our other libraries as reference.
