### ISSUE TITLE
Problem creating transaction

### ISSUE THREAD

**Issue by DanielDedaInsight** [BlockIo/block_io-csharp#9]
I've been using the .NET library to create and submit the transactions in the BTC network. But the transactions returned erros for Insuficient Funds.

```
var blockIo = new BlockIo("our_api_key", "our_account_pin");

//Preparation method:
var prep = blockIo.PrepareTransaction(new { amounts = "0.00110935", to_addresses = "address"});

//Checking the prepared transaction:
var check = blockIo.SummarizePreparedTransaction(prep);

// Creating the transaction
var transaction = blockIo.CreateAndSignTransaction(prep);
```

After the execution of "SummarizePreparedTransaction" the value on the returning object is "110935.0000000" and not "0.00110935", the network fees are inccorect in the same way.
And if running "CreateAndSignTransaction" the returned error message is "Not enough funds to cover the target with missing amount 4304.99995695"

**Comment by doersf** [comment]
Are you encountering the same issue when you use the Bitcoin Testnet or Litecoin Testnet?

We are currently unable to replicate your issue using .NET Core SDK (3.1.411).

**Comment by DanielDedaInsight** [comment]
Using the Bitcoiun Testnet I received the same response

The response from the PrepareTransaction method:
`{{
  "network": "BTCTEST",
  "tx_type": "basic",
  "inputs": [
    {
      "input_index": 0,
      "previous_txid": "f6f460c23b225a7222b979210cca7456a53b04216676d13c54302cc24cbdd0c3",
      "previous_output_index": 0,
      "input_value": "0.00100000",
      "spending_address": "2N6ic3Kv6iiZvXzb4cjLZMB3HH4S6VuRGCK"
    }
  ],
  "outputs": [
    {
      "output_index": 0,
      "output_category": "user-specified",
      "output_value": "0.00010000",
      "receiving_address": "mkHS9ne12qx9pS9VojpwU5xtRd4T7X7ZUt"
    },
    {
      "output_index": 1,
      "output_category": "change",
      "output_value": "0.00086880",
      "receiving_address": "2N6ic3Kv6iiZvXzb4cjLZMB3HH4S6VuRGCK"
    }
  ],
  "input_address_data": [
    {
      "required_signatures": 2,
      "public_keys": [
        "02484fbd76802c52c43d6b86801c4ff27e66f718532162dbe8d179fbd049e2551d",
        "03cdf54ad1ec5fd81a60a36cbd377e1aa1a99e128e2be07785febdc683fc2fb1c3"
      ],
      "address": "2N6ic3Kv6iiZvXzb4cjLZMB3HH4S6VuRGCK",
      "address_type": "P2WSH-over-P2SH"
    }
  ],
  "user_key": {
    "public_key": "03cdf54ad1ec5fd81a60a36cbd377e1aa1a99e128e2be07785febdc683fc2fb1c3",
    "encrypted_passphrase": "P6U25bj7XuX1iGVl/nh9RHjIDzIQn0T6Q1U7t3i//xnQiyQpeMLjPs5gFRSNGNitEMhi2g1dUxugipj3kRxaxetzd69NGKL7fVaiUHMYAwdvHxEWs5FhgY4LPtk9z5UApDEh3WUExi59UdGxgrZMSDSryPzWYsTF5/wu4MpuSDA=",
    "algorithm": {
      "pbkdf2_salt": "c232bac2fc2824233dd44c19c78b0994",
      "pbkdf2_iterations": 102400,
      "pbkdf2_hash_function": "SHA256",
      "pbkdf2_phase1_key_length": 16,
      "pbkdf2_phase2_key_length": 32,
      "aes_iv": "bef83e224c5c28ee572200f8",
      "aes_cipher": "AES-256-GCM",
      "aes_auth_tag": "f061af3737705416ee0fc4babc110832",
      "aes_auth_data": ""
    }
  },
  "estimated_tx_size": 208,
  "expected_unsigned_txid": "e1aa06ed0296cd6ee208c88c50922e0037a3b2979b09ff8390c9e44451c0867b"
}}`

The response from SummarizePreparedTransaction method:

`{
    "network": "BTCTEST",
    "network_fee": "3120,00000000",
    "blockio_fee": "0,00000000",
    "total_amount_to_send": "10000,00000000"
}`

**Comment by doersf** [comment]
This should be resolved in the current master. If we do not hear back in the next 24 hours, we expect to tag this release as a fix.

**Comment by nwasiq** [comment]
Fixed in the current master, tagged as release 2.0.2
